### ISSUE TITLE
Can not run neo4j with plugin. Failed to start.

### ISSUE THREAD

**Issue by turbologistik** [graphaware/neo4j-to-elasticsearch#85] opened 2017-10-02 11:51 UTC
When i added plugins(reco, timetree v 3.2.5), changed neo4j.conf and launched neo4j, i got exception:

Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@67d40e8c' was successfully initialized, but failed to start. Please see the attached cause exception "The ResourceConfig instance does not contain any root resource classes.".

Configuration:
1. Windows 10
2. elastic 5.6
3. Neo4j 3.2.5

**Comment by turbologistik** [comment] 2017-10-02 13:50
2017-10-02 13:48:41.324+0000 WARN [o.n.i.p.PageCache] The dbms.memory.pagecache.size setting has not been configured. It is recommended that this setting is always explicitly configured, to ensure the system has a balanced configuration. Until then, a computed heuristic value of 3302543360 bytes will be used instead. 
2017-10-02 13:48:41.871+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.reco.neo4j.module.RecommendationModuleConfiguration` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-reco-3.2.5.51.11.jar`: com/graphaware/runtime/config/BaseTimerDrivenModuleConfiguration
2017-10-02 13:48:41.871+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.reco.neo4j.module.RecommendationModule` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-reco-3.2.5.51.11.jar`: com/graphaware/runtime/module/BaseTimerDrivenModule
2017-10-02 13:48:41.871+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.reco.neo4j.engine.RandomRecommendations` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-reco-3.2.5.51.11.jar`: com/graphaware/runtime/walk/NodeSelector
2017-10-02 13:48:41.871+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.reco.neo4j.module.RecommendationModuleBootstrapper` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-reco-3.2.5.51.11.jar`: com/graphaware/runtime/module/RuntimeModuleBootstrapper
2017-10-02 13:48:41.871+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.api.TimedEventsApi` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/api/json/JsonNode
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.module.TimeTreeModule` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/runtime/module/BaseTxDrivenModule
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.merge is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.range is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.single is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.now is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.module.TimeTreeModule$1` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/tx/executor/batch/UnitOfWork
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.module.TimeTreeModule$2` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/tx/executor/single/TransactionCallback
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.events.range is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.events.attach is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] ga.timetree.events.single is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.api.TimeTreeApi` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/api/json/JsonNode
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.module.TimeTreeConfiguration` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/runtime/config/BaseTxDrivenModuleConfiguration
2017-10-02 13:48:41.886+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/runtime/module/BaseRuntimeModuleBootstrapper
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.timetree.api.EventVO` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-timetree-3.2.5.51.27.jar`: com/graphaware/api/json/LongIdJsonNode
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.uuid.UuidConfiguration` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-uuid-3.2.5.51.14.jar`: com/graphaware/runtime/config/BaseTxDrivenModuleConfiguration
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.uuid.UuidModule` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-uuid-3.2.5.51.14.jar`: com/graphaware/runtime/module/BaseTxDrivenModule
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.uuid.generator.JavaUtilUUIDGenerator` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-uuid-3.2.5.51.14.jar`: com/graphaware/common/uuid/UuidGenerator
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.uuid.UuidBootstrapper` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-uuid-3.2.5.51.14.jar`: com/graphaware/runtime/module/RuntimeModuleBootstrapper
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.uuid.api.UuidApi` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-uuid-3.2.5.51.14.jar`: com/graphaware/runtime/config/BaseTxDrivenModuleConfiguration
2017-10-02 13:48:41.902+0000 WARN [o.n.k.i.p.Procedures] Failed to load `com.graphaware.module.uuid.generator.SequenceIdGenerator` from plugin jar `~/Documents/Neo4j/default.graphdb/plugins/graphaware-uuid-3.2.5.51.14.jar`: com/graphaware/common/uuid/UuidGenerator

**Comment by ikwattro** [comment] 2017-10-02 14:54
Did you add neo4j-framework as well? Please also paste your configuration file.

**Comment by turbologistik** [comment] 2017-10-03 07:34
This is my config

**Comment by ikwattro** [comment] 2017-10-03 07:39
> What you mean "add neo4j-framework as well"?

I mean to read the documentation we provide, this is written in ALL our modules : 

https://github.com/graphaware/neo4j-to-elasticsearch#server-mode

https://github.com/graphaware/neo4j-timetree#server-mode

**Comment by turbologistik** [comment] 2017-10-03 07:45
Yes of course, i was read documentation. But, i can't launch application.

**Comment by ikwattro** [comment] 2017-12-18 20:01
Closing as the error is showing the missing framework jar, feel free to re-open if the issue is still there with the lists of the plugins you installed.

**Closed by ikwattro** 2017-12-18 20:01 UTC
